GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZWZkNTNiZS1jYTJiLTQ3NDktOGM1MC0wNTVhZWE4NDQ0NjUiLCJpYXQiOjE3NjAxOTY2OTcsImV4cCI6MTc2MDE5NjcxMn0.7kMEXmU5TjO5ZaHZYTr1Zg301P0gUCP4iVHTlktEz-g

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
	"nickname": "user one",
	"username": "myusername",
	"password": "mypassword"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
	"username": "myusername",
	"password": "mypassword"
}

###

POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{
 	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZWZkNTNiZS1jYTJiLTQ3NDktOGM1MC0wNTVhZWE4NDQ0NjUiLCJpYXQiOjE3NjAxOTcwMDR9.N6xP07yH1I4XeCSsDHGOUfJlEZ78-8J0lVI3O91g9bU"
}

###

DELETE http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZWZkNTNiZS1jYTJiLTQ3NDktOGM1MC0wNTVhZWE4NDQ0NjUiLCJpYXQiOjE3NjAxOTcwMDQsImV4cCI6MTc2MDE5NzAxOX0.XCLyWCmDleQu3j8JCf4LQlSHb4CO8wA7cpi1TdGfvPk
